---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-helm-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-helm
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      # - "pods/portforward"
      - "jobs"
      - "pods"
      - "secrets"
      - "configmaps"
      - "services"
      - "statefulsets"
      - "deployments"
    verbs:
      - "get"
      - "update"
      - "create"
      - "delete"
      - "list"
      - "watch"
      - "patch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-helm
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: gitlab-helm
subjects:
  - kind: ServiceAccount
    name: gitlab-helm-account
    namespace: default
