---
apiVersion: v1
kind: Service
metadata:
  name: edgedb
  labels:
    type: database
    area: backend
spec:
  clusterIP: "None"
  selector:
    app: edgedb
  ports:
    - name: binary
      port: 5656
      targetPort: binary

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgedb
  labels:
    type: database
    area: backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: edgedb
      type: database
      area: backend
  template:
    metadata:
      labels:
        app: edgedb
        type: database
        area: backend
    spec:
      containers:
        - name: edgedb
          image: edgedb/edgedb:2020080601441383e9f5
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /var/lib/edgedb/data
          ports:
            - name: binary
              containerPort: 5656
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: edgedb-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgedb-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: edgedb-data
  local:
    path: /home/modbay/edb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - modbay

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgedb-data
spec:
  storageClassName: edgedb-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
