---
apiVersion: v1
kind: Service
metadata:
  name: edgedb
  labels:
    type: database
    area: backend
spec:
  clusterIP: "None"
  selector:
    app: edgedb-bd
  ports:
    - name: binary
      port: 5656
      targetPort: binary

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgedb
  labels:
    type: database
    area: backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: edgedb-bd
      type: database
      area: backend
  template:
    metadata:
      labels:
        app: edgedb-bd
        type: database
        area: backend
    spec:
      containers:
      - name: edgedb
        image: edgedb/edgedb:202006200336058d78f4
        imagePullPolicy: Always
        volumeMounts:
          - name: edgedb
            mountPath: /var/lib/edgedb/data
        ports:
        - name: binary
          containerPort: 5656
      volumes:
        - name: edgedb
          persistentVolumeClaim:
            claimName: modbay-edgedb-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: modbay-edgedb
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: modbay-edgedb-storage
  local:
    path: /home/modbay/edb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: In
          values:
            - modbay

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modbay-edgedb-claim
spec:
  storageClassName: modbay-edgedb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
