---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    type: cache
    area: backend
spec:
  clusterIP: "None"
  selector:
    app: redis
  ports:
    - name: tcp
      port: 6379
      targetPort: tcp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    type: cache
    area: backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: redis
      type: cache
      area: backend
  template:
    metadata:
      labels:
        app: redis
        type: cache
        area: backend
    spec:
      containers:
        - name: data
          image: redis:6-alpine
          imagePullPolicy: Always
          command: ["redis-server"]
          args: ["/config", "--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          ports:
            - name: tcp
              containerPort: 6379
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: modbay-redis-data
        - name: config
          configMap:
            name: modbay-redis-config
            items:
              - key: redis-config
                path: redis.conf

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modbay-redis-data
spec:
  storageClassName: modbay-redis-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: modbay-redis-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: modbay-redis-data
  local:
    path: /home/modbay/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - modbay

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modbay-redis-config
data:
  redis-config: |
    save 900 1
    save 300 10
    save 60 10000
