---
apiVersion: v1
kind: Service
metadata:
  name: modbay-web-backend
spec:
  type: NodePort
  selector:
    app: modbay-worker
    type: web
    area: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbay-worker
  labels:
    type: web
    area: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modbay-worker
      type: web
      area: backend
  template:
    metadata:
      labels:
        app: modbay-worker
        type: web
        area: backend
    spec:
      imagePullSecrets:
        - name: modbay-gitlab-registry-credentials
      containers:
      - name: worker
        limits:
        image: registry.gitlab.com/modbay1/worker
        imagePullPolicy: Always
        env:
        # generic
        - name: MODBAY_WORKER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: modbay-worker-generic
              key: jwt_secret
        # redis
        - name: MODBAY_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: host
        - name: MODBAY_REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: port
        - name: MODBAY_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: db
        - name: MODBAY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        # edgedb
        - name: MODBAY_EDGEDB_HOST
          value: edgedb # edgedb.default.svc.k8s.modbay.net.
        - name: MODBAY_EDGEDB_PORT
          value: "5656" # _binary._tcp.edgedb.default.svc.k8s.modbay.net.
        - name: MODBAY_EDGEDB_USER
          valueFrom:
            secretKeyRef:
              name: edgedb-credentials
              key: user
        - name: MODBAY_EDGEDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: edgedb-credentials
              key: database
        - name: MODBAY_EDGEDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: edgedb-credentials
              key: password
        - name: MODBAY_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: modbay-worker-sentry-credentials
              key: dsn
        volumeMounts:
          - name: config
            mountPath: /code/config.yaml
            # prevent directory override
            subPath: config.yaml
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
      volumes:
        - name: config
          configMap:
            name: modbay-worker-config

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: modbay-worker-config
data:
  config.yaml: |
    worker:
      host: 0.0.0.0
      port: 8080

      domain: https://dev.modbay.net

      jwt_secret: !env MODBAY_WORKER_JWT_SECRET

    redis:
      host: !env MODBAY_REDIS_HOST
      port: !env MODBAY_REDIS_PORT
      db: !env MODBAY_REDIS_DB
      password: !env MODBAY_REDIS_PASSWORD

    edgedb:
      host: !env MODBAY_EDGEDB_HOST
      port: !env MODBAY_EDGEDB_PORT
      user: !env MODBAY_EDGEDB_USER
      database: !env MODBAY_EDGEDB_DATABASE
      password: !env MODBAY_EDGEDB_PASSWORD

    sentry:
      enabled: true
      debug: false
      dsn: !env MODBAY_SENTRY_DSN
